config/routes.rb
Rails.application.routes.draw do

  # get "restaurants", to: "restaurants#index"
  # get "restaurants/new", to: "restaurants#new"
  # post "restaurants", to: "restaurants#create"
  # get "restaurants/:id", to: "restaurants#show", as: :restaurant
  # get "reviews/new", to: "reviews#new", as: :
  # post "reviews", to: "reviewsts#create"
  resources :restaurants do
    resources :reviews
  end
end



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates_presence_of :category, :name, :address
  validates :category, inclusion: { in: %w[japanese chinese italian belgian french] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates_presence_of :content, :rating
  validates :rating, inclusion: { in: 0..5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end



# need a route so visitor can add a new restaurant, and be redirected to the show view of the new restaurant
# refers to GET "restaurants/new"
# POST "restaurants"










# need a route so the visitor can see the details of a restaurant with all the reviews related to the restaurant

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end

end








# need a route so the visitor can add a new review to a restaurant

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>

<%= link_to "Add a new Restaurant",  new_restaurant_path(@restaurant) %>

<% @restaurants.each do |restaurant| %>
<li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
<% end %>

app/views/restaurants/new.html.erb
<h1>Add A New Restaurant</h1>


<%= form_for(@restaurant) do |f| %>
<%= f.label :name, class: 'form-label'  %>
<%= f.text_field :name, class: 'form-control' %>
<%= f.label :address, class: 'form-label' %>
<%= f.text_field :address, class: 'form-control' %>
<%= f.label :category, class: 'form-label' %>
<%= f.text_field :category, class: 'form-control' %>
<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/show.html.erb
<h1>The Individual Restaurant You Chose </h1>
<h2><%= @restaurant.name %></h2>

<h3><%= link_to "Add a Review", new_restaurant_review_path(@restaurant)%></h3>

app/views/reviews/new.html.erb
<h1>Add A New Review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>